spring.application.name=websocket

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypassword

# Auto reset and create database when running app
spring.jpa.hibernate.ddl-auto=update

# First create tables, then insert data
spring.jpa.defer-datasource-initialization=true

# Initialize data with app start
spring.sql.init.mode=always

# Data location
spring.sql.init.data-locations=classpath:sql/database_test_data.sql