package pus.projekt.websocket.enums;

public enum ErrorCode {
    BAD_SYNTAX,
    MISSING_FIELD,
    UNKNOWN_TYPE,
    UNKNOWN_ACTION,
    INVALID_DATA_TYPE,
    VALIDATION_ERROR,
    INVALID_PACKET_ID,
    BAD_VERSION,
    UNAUTHORIZED,
    TOKEN_EXPIRED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    TOO_MANY_REQUESTS,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE
}
